# Generated by Django 3.2.4 on 2021-06-11 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('relationship_status', models.CharField(choices=[('married', 'Married'), ('unmarried', 'Unmarried')], max_length=20)),
                ('children', models.IntegerField()),
                ('address', models.CharField(max_length=400)),
                ('profession', models.CharField(max_length=20)),
                ('blood_group', models.CharField(max_length=10)),
                ('height', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('blood_pressure', models.CharField(max_length=20)),
                ('allergies', models.CharField(max_length=200)),
                ('sugar_level', models.CharField(max_length=20)),
                ('routine_medications', models.CharField(max_length=200)),
                ('surgical_history', models.CharField(max_length=200)),
                ('other_details', models.CharField(max_length=200)),
                ('em_contact_name', models.CharField(max_length=100)),
                ('em_phone', models.CharField(max_length=20)),
                ('is_in_healthcare', models.BooleanField()),
                ('healthcare_catagory', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
